### ISSUE TITLE
Show correct user profile image in comment

### ISSUE THREAD

**Issue by ThangLeQuoc** [cuongnm265/frog-coffee-news#101]
User gravatar is incorrect because of using static image
![image](https://user-images.githubusercontent.com/20574640/26859455-0357a4ba-4b62-11e7-90ad-eb64ad95ef84.png)

**Comment by ThangLeQuoc** [comment]
Cái khúc này tên gì ? Nằm ở component nào vậy mậy ? T tìm không ra
![image](https://user-images.githubusercontent.com/20574640/26859476-27588d8e-4b62-11e7-8176-5d9dc1b65cab.png)

**Comment by ThangLeQuoc** [comment]
À rồi, thấy rồi, trong `user.component`
![image](https://user-images.githubusercontent.com/20574640/26859731-01410e4e-4b64-11e7-8cd5-4f6f636f36e2.png)

**Comment by ThangLeQuoc** [comment]
Chưa xong đâu mà close :))

**Comment by cuongnm265** [comment]
Biết cách sửa rồi mà, close chứ để làm gì =))

**Comment by cuongnm265** [comment]
ơ đ, lấy acc t reopen hả =))

**Comment by ThangLeQuoc** [comment]
ủa sửa sao ?, đâu phải src cứ để `auth.userProfiile.image` được. Lúc m coi comment của những thằng khác thì nó lấy profile kiểu gì ? :))z
Đang nghịch mấy cái auth0 user, tiện tay =))

**Comment by cuongnm265** [comment]
Thêm field vô object trong participants chứ sao giờ, mà ngon thì thêm mỗi email thôi, xong gọi api lấy gravatar

**Comment by cuongnm265** [comment]
Bản chất méo liên quan =)), nó có liên quan gì tới auth0 nữa đâu, chỉ cần email là lấy được cái img url của user rồi

**Comment by ThangLeQuoc** [comment]
ủa có API à ? Đâu ?

**Comment by ThangLeQuoc** [comment]
T định sửa lại cái `user-model`,  cho thêm trường `profile_image `nữa, lúc đầu mặc định là url gravatar, sau thằng user có thể đổi profile image, up hình lên đổi các kiểu.

**Comment by cuongnm265** [comment]
https://vi.gravatar.com/site/implement/images/

**Comment by ThangLeQuoc** [comment]
@cuongnm265  ^ chưa làm vụ custom user profile gì đồ nữa
![image](https://user-images.githubusercontent.com/20574640/26862832-7756fa9e-4b78-11e7-8bb2-9246b00bfc3a.png)

**Comment by cuongnm265** [comment]
hồi hôm nói dẹp vụ đó rồi mà =))

**Comment by ThangLeQuoc** [comment]
Giờ có một số chiến thuật sau =))

1. Tạo một phương thức api lấy `gravatar_url `phía backend, đầu vào là `user_id`, thì cái phương thức trên `comment.component` cũng sẽ giống như thế này
![image](https://user-images.githubusercontent.com/20574640/26863640-1c09fdb6-4b7e-11e7-9129-3e4832cf5962.png)
_**Ưu**_: làm được, nhanh
**_Nhược_**:  khá nhiều request, mỗi một cái comment là một cái request lấy hình. Bao nhiêu comment là bấy nhiêu request lấy hình. 

2. Cái `discussion` khi gọi request lấy discussion theo `article_id`, thì với mỗi cái comment của từng `user_id`, phải **inject** thêm cả `profile_image` bằng cách lấy kết bên collection `users`.
**_Ưu_**: Business Logic chặt chẽ nhất (tự phỏng đoán 👶 ), nếu thằng user này có thay đổi avatar custom của nó trên trang thì vẫn nhận được thay đổi sau này.
**_Nhược_**: Dài dòng, phức tạp, cực kì tốn thời gian làm 🐶 , vì còn phải thêm `profile_image` vô `user-model`, sau khi `sign-up` thì mặc định trường này là `gravatar_url`, giả sử sau này thằng đó hứng máu up avatar riêng thì thay bằng Amazon S3 url.

Nói chung giờ làm đối phó ⏰ thì làm cách **1** , còn nếu làm nghiệp vụ lâu dài thì cách **2** hợp lí hơn. 🍰

**Comment by ThangLeQuoc** [comment]
Đm ai đó khen tôi đi, quá đẹp, quá mượt 😆 
![image](https://user-images.githubusercontent.com/20574640/26876699-9a30252a-4bb1-11e7-8509-cfebaf2142d3.png)

Resolved in latest pull request ❤️

**Comment by cuongnm265** [comment]
Nếu close nhớ ref nó vô, hoặc trong cái merge PR ý, m gõ kiểu này nè
`close #101`

**Comment by cuongnm265** [comment]
@ThangLeQuoc 
[http://imgur.com/pB6zZwp](bug)

**Comment by cuongnm265** [comment]
```
user.service.ts:56 An error occurred Response {_body: "Invalid ObjectId", status: 404, ok: false, statusText: "Not Found", headers: Headers…}
```

**Comment by ThangLeQuoc** [comment]
M ghi các bước thực hiện coi, để t làm lại thử

**Comment by cuongnm265** [comment]
User chưa login là bug

**Comment by cuongnm265** [comment]
Thêm cái nữa là user logout rồi nhưng cái noti nó vẫn còn (có vẻ noti không sync được)

**Comment by ThangLeQuoc** [comment]
Resolved in #103 
Còn cái vụ user notification nó không sync thì tạo issue khác đi, t (tìm cách) sửa cho

**Comment by ThangLeQuoc** [comment]
Ngay khi vào một article , khi user chưa đăng nhập
![image](https://user-images.githubusercontent.com/20574640/26913281-082ef5e6-4c44-11e7-9899-a12a4b41e780.png)

Và khi đăng nhập, vẫn ngay trên article đó luôn
![image](https://user-images.githubusercontent.com/20574640/26913315-3130250a-4c44-11e7-83eb-07f9433d5042.png)

Nó không lấy ảnh được, vì t lấy ảnh ở đoạn `ngOnInit`
Vậy làm sao để bắt được sự kiện đăng nhập ngay trên article đó để tạo request lấy ảnh nhỉ ? @cuongnm265

**Comment by thanglequoc** [comment]
Đã khử  🔼  🐛 qua commit  #104
