### ISSUE TITLE
Article tag is ready to use

### ISSUE THREAD

**Issue by ThangLeQuoc** [cuongnm265/frog-coffee-news#62]
Giờ trong Editor, người dùng có thể chọn tag từ một danh sách có trước, mà cái danh sách này là cứng trong database luôn, chứ chưa có vụ tạo tag mới, hay suggest tag cho admin các kiểu.

Cái vụ tag này bị duplicate một cái là lúc chỉnh sửa một article đã có tag, thì cái autocomplete nó không tự bỏ những cái tag đã có sẵn (thông qua ngModel), mà nó vẫn cho add lại tag đã có sẵn, gây trùng lặp.

Giờ bạn Cường chỉnh lại article detail cho nó hiện tag nhé, cấu trúc một cái tag trong article nó thế này.

![image](https://cloud.githubusercontent.com/assets/20574640/26432973/c18749f6-4129-11e7-8485-283571f6b130.png)

**Comment by cuongnm265** [comment]
Tức là cái issue này là m nói cho t biết thôi đúng không, lúc làm không quan tâm tới nó là được ha. Bây giờ có thể chơi cách kiểu này, không resolve issue được nhưng t nghĩ là chấp nhận được: 
Giờ nếu nó cho chọn lại các tag đã có đúng k, thì trong phần submit mình làm thêm 1 đoạn check nữa, check cái (array) list các tag đó, xong check nếu cái nào dup thì bỏ ngay từ đó luôn, xuống server nó sẽ không bị nữa, đúng không

**Comment by ThangLeQuoc** [comment]
![image](https://cloud.githubusercontent.com/assets/20574640/26481132/0dda5d18-4209-11e7-84e2-e8fe4af52fda.png)
NgModel nó không sync với đống autocomplete, nên vẫn chọn được tag đã có sẵn, hậu quả nó sẽ thế này
![image](https://cloud.githubusercontent.com/assets/20574640/26481157/32306158-4209-11e7-8922-af3e69f58a31.png)

Vậy t sẽ resolve duplicate ở phía backEnd vậy. Nhưng cái issue này nếu không sửa được thì lúc làm, hay demo thì nhớ né cái trường hợp này ra.

**Comment by cuongnm265** [comment]
Ừ thì nó thêm thì kệ nó thôi, miễn lần sau show lên thì phía backend đã xử lí và exclude mấy cái dup trước là ok
