### ISSUE TITLE
DELETE Article Resquest remove the article permenantly

### ISSUE THREAD

**Issue by ThangLeQuoc** [cuongnm265/frog-coffee-news#64]
Gửi request delete article là backEnd nó findByIdAndRemove, tức là xoá vĩnh viễn luôn. 
Ngày trước t nhớ t đã sửa thành deletedAt rồi mà nhỉ.

Vậy trên frontEnd m có dùng deletedAd nữa không ?

**Comment by cuongnm265** [comment]
Hiện tại trên frontend chỉ list các article có thôi, và hình như lúc remove thì nó mất luôn, nên cái deleteAt nó đâu có ý nghĩa. Khi nào có deleteAt thì sẽ check = cách đó

**Comment by ThangLeQuoc** [comment]
Cho nó giải tán luôn.
