### ISSUE TITLE
Empty author information in Article Editor

### ISSUE THREAD

**Issue by ThangLeQuoc** [cuongnm265/frog-coffee-news#65]
Cái article editor nếu trường `Current User` để trống thì cái field `author `trong request body nó cũng trống hoác theo luôn. Nếu không có Author thì mặc định chỉ định author đang là thằng viết article đó luôn đi.
![image](https://cloud.githubusercontent.com/assets/20574640/26481353/a1d7782e-420a-11e7-8626-81452c348ea3.png)

**Comment by cuongnm265** [comment]
Vậy sẽ để mặc định là vậy và không cho nó sửa luôn

**Comment by ThangLeQuoc** [comment]
Ý là ,
Giả sử tác giả gốc của bài đăng (mình đăng bài kiểu như trích dẫn lấy nguồn), thì mình để tên của nó.
Còn nếu bài đó là do trang của mình tự viết, thì author để là tên của mình luôn.

**Comment by cuongnm265** [comment]
Nó có cái source mà, trích dẫn phải để đó mới hợp lí chứ

**Comment by ThangLeQuoc** [comment]
Ví dụ thằng Võ Trọng Nhân nó là phóng viên báo Tuổi Trẻ chẳng hạn,
Thì 
Source : Tuổi Trẻ
Author: Võ Trọng Nhân

**Comment by cuongnm265** [comment]
#71
