### ISSUE TITLE
Article Editor doesn't redirect after create/update article successfully

### ISSUE THREAD

**Issue by ThangLeQuoc** [cuongnm265/frog-coffee-news#66]
Cái Article Editor lúc tạo hoặc sửa một cái article thành công thì phải redirect là ngoài component article list này luôn. Chứ đã tạo/ sửa thành công mà vẫn trơ ở đó thì hơi sai sai.

![image](https://cloud.githubusercontent.com/assets/20574640/26481510/a666fe04-420b-11e7-8c8c-8b34e6bb0420.png)

**Comment by cuongnm265** [comment]
Ok + thông báo tạo thành công = snackbar

**Comment by ThangLeQuoc** [comment]
Redirect sau khi cái snackbar đó nổi lên được không ?
