### ISSUE TITLE
Update Article - Tag object in Tags collection doesn't remove that article_id if remove tag from that article

### ISSUE THREAD

**Issue by ThangLeQuoc** [cuongnm265/frog-coffee-news#67]
Khi Update article , gặp trường hợp xoá một tag của article này thì trong `Tags Collection`, cái `Articles Array` phải `pop ` cái article_id của thằng này ra. Và phải resolve trên tất cả các tag đã bị gỡ.
![image](https://cloud.githubusercontent.com/assets/20574640/26481693/1cd9a00e-420d-11e7-889a-ef7b31d77834.png)

**Comment by cuongnm265** [comment]
Need more info

**Comment by ThangLeQuoc** [comment]
Solved in latest commit
