### ISSUE TITLE
Landing page category is a bit stupid because of missing tiles

### ISSUE THREAD

**Issue by ThangLeQuoc** [cuongnm265/frog-coffee-news#91]
Cái landing page, scroll category thì trông ổn rồi, nhưng lúc sang trang 2, nó bị mất 2 ô, trông thấy gớm. 

Vậy t đề xuất 2 cách giải quyết, bạn Cường có thể đóng góp thêm:
**1 - Tạo thêm 2 cái category nữa để lấp vô 2 cái ô đó, lúc đó sẽ đẹp.**
            Ứng viên
      **Transports** - chuyên về Car, Automotive, Motorbike. Chuyên mục này đa số chuyên trang công nghệ đều có
      **Science** - chuyên mục về khoa học, gồm các bài đăng về các mục như vũ trụ, năng lượng sinh hoạt, và môi trường
**2 - Sửa lại giao diện , mà chưa biết sửa thế nào.**

**Comment by cuongnm265** [comment]
Vậy thêm 2 cái thôi, chứ 2 cái thiếu kia t chèn cái hình trống vô đó, là đáng ra là cái hình `coming soon` thiệt đep, mà kiếp không ra =))
Mà nếu như m nói thôi dẹp mẹ 2 cái kia luôn đi, đê 1 cái landing 4 cat là đẹp luôn.

**Comment by ThangLeQuoc** [comment]
V để t thêm hai cái Category như đã nói ở trên, tại cái vụ trượt trượt đó nhìn hay.  =))

Với lại mấy cái ảnh nền nhìn đẹp đó

**Comment by cuongnm265** [comment]
tên nền m muốn + flat design, mà mấy cái ratio hình như k đúng nên nó giãn hình, rảnh thì kiếm lại cho đẹp
