### ISSUE TITLE
Rework information of articles on landing page

### ISSUE THREAD

**Issue by ThangLeQuoc** [cuongnm265/frog-coffee-news#95]
Cái landing page hiện tại có 2 chỗ như t đánh dấu sau:

1 - Chỗ này nên đặt moment thì hay hơn, để người dùng biết tin này đăng từ mấy ngày trước, chứ để giờ đăng thì không ý nghĩa lắm
2 - Cái này là số lượng comment trong bài đúng không ? Nếu cần thì t update lại model article rồi thêm thuộc tính này vào , sửa lại mớ phương thức nữa.

![image](https://cloud.githubusercontent.com/assets/20574640/26783900/d686ceb8-4a24-11e7-80e3-6de92fd80e88.png)

**Comment by cuongnm265** [comment]
1. Thường thì t thấy mấy trang báo bài nó đăng liên tục, nên những tin trên landing là bài gần nhất trong ngày rồi, nếu vậy mà để ngày là nó sẽ trùng ngày hết. Còn cái của mình là có vẻ tại ít bài quá nên vậy đó
2. Nếu update comment có bài đó mà k cần xử lí backend nhiều bằng cái t đang làm thì khỏi cũng đc

**Comment by ThangLeQuoc** [comment]
Cái chỗ **1** đó để kiểu time ago ấy, như Just now, 3 minutes ago, gì gì đó, chứ để ngày làm chi :)))

2 - Vụ tăng số comment trong bài đó thì khi nào có người comment lên bài đó thì gọi request update article, đẩy cái biến comment_count lên thôi. Xoá comment thì ngược lại, request update giảm cái biến đó xuống, nói chung không phức tạp lắm. Giả sử t không đếm comment thì m đếm kiểu gì ? Tạo request gọi discussion à ?

**Comment by cuongnm265** [comment]
1. got it
2. Hình như có implement code cái vụ đó rồi, mà sao nó toàn 0 k nhớ nữa =))

**Comment by ThangLeQuoc** [comment]
Resolved =))z
